name: 'Run gradle publish'
description: 'Publish the current build to GitHub Packages'

inputs:
  GITHUB_TOKEN:
    description: 'Service account access token that allows publishing packages'
    required: true
  GITHUB_ACTOR:
    description: 'Service account username that allows publishing packages'
    required: true
  package-version:
    description: 'Package Version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish API package
      id: maven-publish
      run: |
        echo "Package Version = ${INPUT_PACKAGE_VERSION}"
        
        ./gradlew \
          :modules:api:publish \
          -PpackageVersion=$INPUT_PACKAGE_VERSION
      shell: bash
      env:
        CI: true
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ inputs.GITHUB_ACTOR }}
        INPUT_PACKAGE_VERSION: ${{ inputs.package-version }}
