#!/usr/bin/env bash

# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

# Lint the project via the script. Include unit test suite. Don't use OWASP dependency checker.
.sh/lintProject.sh "unit" ""
