/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
public object Libs {
    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val ktlint_reporter_baseline: String =
            "com.pinterest.ktlint:ktlint-reporter-baseline:_"

    public const val ktlint_ruleset_standard: String =
            "com.pinterest.ktlint:ktlint-ruleset-standard:_"

    public const val ktlint: String = "com.pinterest:ktlint:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:_"

    public const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:_"
}
