#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

# Applicable values:
# "unit" - Runs only the unit tests
# "instrumentation" - Runs only the instrumentation tests
# "both" - Runs both unit and instrumentation tests
# Any other value, including character casing differences, won't run the tests
TEST_RUNNER_MODE="$1"

find ./config/hooks -type f -exec shellcheck {} +
find ./scripts -type f -exec shellcheck {} +

./gradlew \
  :buildLogic:plugins:detekt \
  detekt \
  :buildLogic:plugins:ktlintCheck \
  ktlintCheck \
  vale

# Optionally run testing suites based on the provided runner mode
if [[ $TEST_RUNNER_MODE == "unit" ]]
then
  ./gradlew testDebugUnitTest
elif [[ $TEST_RUNNER_MODE == "instrumentation" ]]
then
  ./gradlew \
    googleAtdPixelXLApi33DebugAndroidTest \
    -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect

elif [[ $TEST_RUNNER_MODE == "both" ]]
then
  ./gradlew \
    googleAtdPixelXLApi33DebugAndroidTest \
    testDebugUnitTest \
    -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect
fi
