package uk.gov.logging.api.analytics.extensions

import android.content.Context
import android.content.res.Configuration
import androidx.annotation.PluralsRes
import androidx.annotation.StringRes
import java.util.Locale

@Suppress("AppBundleLocaleChanges") // Needs to be dealt with in App
private val Context.englishConfiguration: Configuration
    get() = Configuration(resources.configuration).apply { setLocale(Locale.ENGLISH) }

/**
 * Extension function to get the English versions of resource strings regardless of the language
 * the user's device is in.
 *
 * When using getEnString in One Login the resources id is returned,
 * hence a new method has been created. Unsure of how or why the original issue exists as
 * it's used extensively in the id-check project.
 *
 * @param id String resource ID.
 * @param formatArgs Any additional arguments to format the string.
 */
fun Context.getEnglishString(
    @StringRes id: Int,
    vararg formatArgs: Any,
): String = with(createConfigurationContext(englishConfiguration)) { getString(id, *formatArgs) }

/**
 * Extension function to get the English versions of resource quantity strings regardless of the
 * language the user's device is in.
 *
 * @param id – The desired resource identifier, as generated by the aapt tool. This integer encodes
 * the package, type, and resource entry. The value 0 is an invalid identifier.
 * @param quantity – The number used to get the correct string for the current language's plural rules.
 * @param formatArgs – The format arguments that will be used for substitution.
 */
fun Context.getEnglishQuantityString(
    @PluralsRes id: Int,
    quantity: Int,
    vararg formatArgs: Any,
): String =
    with(createConfigurationContext(englishConfiguration)) {
        resources.getQuantityString(id, quantity, *formatArgs)
    }
