name: On Branch Push (non-develop/release/main)

on:
  push:
    branches:
      - "**"
      - "!develop"
      - "!release/**"
      - "!main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPushJob:
    name: Verify code base when pushed
    runs-on: macos-latest
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    steps:
      - name: Run checkout github action
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Download homebrew dependencies
        run: |
          brew bundle --no-lock
        shell: bash

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Generate version name
        id: version-name
        uses: ./config/actions/version-name
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.latest-tag.outputs.current-tag }}

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}

      - name: Lint script files
        run: |
          ./.sh/lintProject.sh "" "runOwaspDependencyChecker"
        shell: bash

      - name: Bundle reports folder
        uses: ./config/actions/bundle-reports

      - name: Verify Conventional commit standards against latest git tag
        run: |
          cog check
        shell: bash

      - name: Lint script files
        run: |
          shellcheck ./.sh/*
        shell: bash
